const btn = document.querySelector('.btn')
const search = document.querySelector('.search')
const input = document.querySelector('.input')
btn.addEventListener('click',() => {search.classList.toggle('show')
    input.classList.toggle('on')
    // input.classList.replace(display: enabled ;display: blocked )
    input.focus()
}) 
